#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_cadex/version.py`)
CADEX_ELECTRUM_VERSION=${VERSION_STRING[2]}
CADEX_ELECTRUM_VERSION=${CADEX_ELECTRUM_VERSION#\'}
CADEX_ELECTRUM_VERSION=${CADEX_ELECTRUM_VERSION%\'}
export CADEX_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_cadex/version.py`)
CADEX_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
CADEX_ELECTRUM_APK_VERSION=${CADEX_ELECTRUM_APK_VERSION#\'}
CADEX_ELECTRUM_APK_VERSION=${CADEX_ELECTRUM_APK_VERSION%\'}
export CADEX_ELECTRUM_APK_VERSION
